/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Students service. Represents a row in the &quot;test_Students&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.service.model.impl.StudentsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.service.model.impl.StudentsImpl}.
 * </p>
 *
 * @author Tofu
 * @see Students
 * @see com.service.model.impl.StudentsImpl
 * @see com.service.model.impl.StudentsModelImpl
 * @generated
 */
public interface StudentsModel extends BaseModel<Students> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a students model instance should use the {@link Students} interface instead.
	 */

	/**
	 * Returns the primary key of this students.
	 *
	 * @return the primary key of this students
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this students.
	 *
	 * @param primaryKey the primary key of this students
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this students.
	 *
	 * @return the ID of this students
	 */
	public long getId();

	/**
	 * Sets the ID of this students.
	 *
	 * @param id the ID of this students
	 */
	public void setId(long id);

	/**
	 * Returns the first name of this students.
	 *
	 * @return the first name of this students
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this students.
	 *
	 * @param firstName the first name of this students
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this students.
	 *
	 * @return the last name of this students
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this students.
	 *
	 * @param lastName the last name of this students
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the exam fee of this students.
	 *
	 * @return the exam fee of this students
	 */
	public double getExamFee();

	/**
	 * Sets the exam fee of this students.
	 *
	 * @param examFee the exam fee of this students
	 */
	public void setExamFee(double examFee);

	/**
	 * Returns the gender of this students.
	 *
	 * @return the gender of this students
	 */
	public int getGender();

	/**
	 * Sets the gender of this students.
	 *
	 * @param gender the gender of this students
	 */
	public void setGender(int gender);

	/**
	 * Returns the subjects ID of this students.
	 *
	 * @return the subjects ID of this students
	 */
	public int getSubjectsId();

	/**
	 * Sets the subjects ID of this students.
	 *
	 * @param subjectsId the subjects ID of this students
	 */
	public void setSubjectsId(int subjectsId);

	/**
	 * Returns the address of this students.
	 *
	 * @return the address of this students
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this students.
	 *
	 * @param address the address of this students
	 */
	public void setAddress(String address);

	/**
	 * Returns the create date of this students.
	 *
	 * @return the create date of this students
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this students.
	 *
	 * @param createDate the create date of this students
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this students.
	 *
	 * @return the modified date of this students
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this students.
	 *
	 * @param modifiedDate the modified date of this students
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Students students);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Students> toCacheModel();

	@Override
	public Students toEscapedModel();

	@Override
	public Students toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}